__NUMPY INDEXING AND SLICING OF VECTORS__

In [2]:
import numpy as np

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[9]

np.int64(20)

In [8]:
arr[:2]

array([11, 12])

In [9]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
arr_slice = arr[1:8:2]
arr_slice

array([12, 14, 16, 18])

__NUMPY INDEXING AND SLICING OF MATRIX__

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[0]

array([1, 2, 3, 4, 5])

In [17]:
arr[0][1]

np.int64(2)

In [18]:
arr[0,0]

np.int64(1)

In [19]:
arr[0,4]

np.int64(5)

In [20]:
arr[5,4]

np.int64(30)

In [21]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [23]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

__BOOLEAN INDEXING__

In [34]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
bool_index = arr%2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [39]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])