In [2]:
import numpy as np

__Basic Array Creation__

In [23]:
list = [1,2,3,4,5,"Sau",3.22]

In [24]:
list

[1, 2, 3, 4, 5, 'Sau', 3.22]

In [26]:
arr = np.array(list)
arr

array(['1', '2', '3', '4', '5', 'Sau', '3.22'], dtype='<U32')

In [29]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

__Array Generation Function__

In [45]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [41]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.linspace(1,5,2)

array([1., 5.])

In [44]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

__Random Ganeration Functions__

In [47]:
np.random.rand(10)

array([0.98385098, 0.91267899, 0.11911576, 0.33868258, 0.05342601,
       0.24923544, 0.398548  , 0.9532092 , 0.23678046, 0.49604812])

In [48]:
np.random.randn(10)

array([ 0.73373455,  0.45539563,  1.18183315,  0.92097014,  1.11523852,
        0.52495736, -0.15773843,  0.12991075,  1.60914595, -0.31868718])

In [49]:
np.random.randn(10)

array([-1.38141104, -0.45771716,  0.83652127,  1.24148447,  0.8244888 ,
        0.71406188,  0.86591026,  1.01802095,  0.97546413,  1.2490843 ])

In [57]:
np.random.randint(6)

1

In [61]:
np.random.randint(1,9,3,int)

array([8, 2, 2], dtype=int32)

__Array Attributes__

In [64]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr.shape

(3, 3)

In [66]:
arr.size

9

In [67]:
arr.dtype

dtype('int64')

__Array Methods__

In [68]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr.min()

np.int64(1)

In [70]:
arr.max()

np.int64(9)

In [72]:
arr.sum()

np.int64(45)

In [73]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [74]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [75]:
arr.mean()

np.float64(5.0)

In [76]:
arr.std()

np.float64(2.581988897471611)

In [77]:
arr.argmax()

np.int64(8)

In [79]:
arr.argmin()

np.int64(0)

__Reshaping and resizing__

In [82]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [86]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [89]:
new_size = np.resize(arr,(10,3))
new_size

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [90]:
import os
print(os.getcwd())

C:\Users\saura


In [91]:
import os
print(os.path.abspath("Numpy.ipynb"))

C:\Users\saura\Numpy.ipynb
