***ARRAY OPERATIONS***

Arithmetic operations

In [1]:
import numpy as np

In [7]:
a1 = np.array([1,2,3,4,5,])
a2 = np.array([6,7,8,9,10])

In [13]:
arr3 = a1+a2

In [14]:
arr3

array([ 7,  9, 11, 13, 15])

In [15]:
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
a1 % a2

array([1, 2, 3, 4, 5])

In [19]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [26]:
brr = np.arange(1,21).reshape(5,4)

In [27]:
brr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [29]:
crr = brr + 10

In [30]:
crr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [31]:
brr + crr

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50]])

***Arithmetic operations***

***Broadcasting***

In [21]:
l = [10,20,30,40]
arr = np.array(l)

In [23]:
for i in l :
    print(i+10)

20
30
40
50


In [24]:
arr +10

array([20, 30, 40, 50])

In [32]:
arr * 2

array([20, 40, 60, 80])

***Deep and shallow copy***

In [79]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [81]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [82]:
slice * 10

array([10, 20, 30, 40, 50])

In [84]:
slice = a

In [85]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [86]:
b = a

In [87]:
b[0] = 99

In [88]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
b[1:6]*10

array([20, 30, 40, 50, 60])

In [92]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
c = a.copy()

In [94]:
c[1] = 1232

In [95]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [96]:
c * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [102]:
z = a

z * 10

array([990,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [103]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

***Matrix Operations***

In [41]:
mat1 = np.arange(1,10).reshape((3,3))
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
mat2 = np.arange(11,20).reshape(3,3)
mat2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [45]:
mat1*mat2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [44]:
np.dot(mat1,mat2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [52]:
cat1 = np.array([[1,2],
        [3,4]])

In [53]:
cat2 = np.array([[5,6],
        [7,8]])

In [55]:
cat1*cat2

array([[ 5, 12],
       [21, 32]])

In [56]:
cat1 @ cat2

array([[19, 22],
       [43, 50]])

In [57]:
np.dot(cat1,cat2)

array([[19, 22],
       [43, 50]])

***Advance Array Manipulation***

Stacking

In [58]:
cat1

array([[1, 2],
       [3, 4]])

In [59]:
cat2

array([[5, 6],
       [7, 8]])

In [60]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [63]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting

In [71]:
c = np.arange(16).reshape(4,4)

In [72]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [77]:
np.hsplit(c,4)


[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.hsplit()